import { useCallback, useMemo } from 'react';

import { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

import { useAccount, useConnect, useDisconnect } from 'wagmi';

import { Button, Container, Flex } from '@chakra-ui/react';

const Home
  :
  NextPage = () => {
  const { connectors, connectAsync } = useConnect();
  const { address } = useAccount();
  const { disconnectAsync } = useDisconnect();

  const [MetaMaskConnector] = connectors;

  const btnTitle: string = useMemo(() => address ? `Disconnect: ${address}` : 'Connect', [address]);

  const handleConnect = useCallback(async () => {
    try {
      const { chain: { id: chainId } } = await connectAsync({ connector: MetaMaskConnector });
    } catch (e) {
      console.error('Connect err:', e);
    }
  }, [MetaMaskConnector, connectAsync]);

  const handleDisconnect = useCallback(async () => {
    try {
      await disconnectAsync();
    } catch (e) {
      console.error('Disconnect err:', e);
    }
  }, [disconnectAsync]);

  const handleClick = useCallback(async () => {
    if (address) {
      await handleDisconnect();
    } else {
      await handleConnect();
    }
  }, [address, handleConnect, handleDisconnect]);

  return (
    <>
      <Head>
        <title>ethereum-wallet-interface</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container maxW={'1200px'}>
        <Flex flex={1} flexDirection={'column'}>
          <Button onClick={handleClick}>{btnTitle}</Button>
        </Flex>
      </Container>
    </>
  );
};

export default dynamic(() => Promise.resolve(Home), {
  ssr: false,
});
